window.SNAPSHOT = {
 "days": {
  "2026-01-03": "WC Mono Race (Winterberg)",
  "2026-01-04": "WC Two Woman Race (Winterberg)",
  "2026-01-05": "Sprints and lift: St. Mortiz gym (basic strength) Sprint Capacity Plan Connor: \nWarm-Up – Static KN Ham Floss 10 ea. Lateral Squats bed Leg Swings – Linear/Lateral 10 ea.\nCore Primer Alternating Deadbugs 8 ea. Side Plank Leg Lift 15s ea. Bird Dogs 5+5 3s ISO Hold Quadruped Animals 3+3 Tri Touch Glute Bridge March 5+5 3s ISO Hold Tall Kneel Partner Pallof 15s ea.\nMovement Primer Forward Skip w/ Arm Circles 25 yd Backward Skip Cross Body 25 yd Side Slide Arm Swing 8+8 Finish through 30m\nPrep / Primer Heel Scoops + Jog 10+10 Finish through 30m Quad Pulls + Jog 10+10 Start Line Glute Pull w/ Opp Toe Touch + Jog 8+8 Finish through 30m Lunge w/ Spine Circle + Jog 8+8 Start Line\n\nJump + Sprint Prep\nAlt. SL Pogos – Intensive 4x6+6 MB Toss – Countermovement – OH 4x3 Vertical Jump – 90° Rotation 4x2+2 Pogos – Graded – Intensive 4x? MB Throw – Rotational 4x? Vertical Jump – W/ Tuck 4x?\nSprints / Mechanics A-Quick Skips 4x15yd SL B-Skips 4x5+5 Short Shuffle 4x15yd A-Mech Progression 4x20m B-Skip Double Strike 4x20m Long Shuffle 4x20m\nTES Stim (Field) 3x30+10yd RPE 6-7 80-85% 2x30+10yd RPE 7-8 85-90% 1x30+10yd RPE 8-9 90-95%",
  "2026-01-06": "Sauna session: long walk with the boys",
  "2026-01-07": "St. Mortiz gym: Upper Strength / Power Plan Connor:\nPin Press – Multigrip Bar (1/2 Depth) 2x3\nKeiser Chest Press – Countermovement 2x3x2\nMedicine Ball Overhead Slam 2x3\nHeavy squats \nBlock B – Upper Pull Accessory – Core\nChinup 2x4\nKeiser Row – Countermovement 2x3x2\nCopenhagen Plank 2x10s\nCuban Press 2x5ea",
  "2026-01-08": "Accels from Eric old program: 15,20m zones x6",
  "2026-01-09": "Sking St. Mortiz & sports massage (Elana bad crash)",
  "2026-01-10": "WC Mono Race (St. Mortiz)",
  "2026-01-11": "WC Two Woman Race (St. Mortiz)",
  "2026-01-12": "Started back Eric: Long drive St. Moritz to Altenberg Sprint Maintenance:\nHeel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\nA-Skip 1x2 20m \nA-Switch 1x2 20m \nDouble Switch 1x4\nPush Specific ISO 3x5s ea.\nAccels 1x3 10m \nAccels 1x3 20m",
  "2026-01-13": "Strength work Eric: Oscillatory Back Squat 6x2 70lbs\nStanding Squat Drop Jump 6x3\nRDL Drop Catch 4x5\nOverhead Press 4x5",
  "2026-01-14": "Reactive Force:\nMobility Drills 1 Set\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x6\nDeep Tier Gorilla Leaps 2x6\nDeep Tier Split Squat Oscillations 4x12\nDeep Tier Split Exchange Leaps 2x12",
  "2026-01-15": "Sprint Maintenance: (SO MUCH STRESS)\nHeel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\n\n-\n\nMobility Drills 1 Set Dribble Series 1x8 20m Scissor Bounds 1x3 20m Walk-In Sprints 1x5 40m",
  "2026-01-16": "Altenberg Bobsled Pushing: Heel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\n\n-\nMobility Drills 1 Set\nDL Pogo Jump 2x20\nDL Pogo w/ Intermediate Jump 2x20\nDeep Tier 2Fwd 1Bwd 2x12\nConsecutive Broadjumps 3x5\nLinear SL Hops 4x5\nPush Specific ISO 3x5s ea\nSingle Pushes 1x6 45m full depth",
  "2026-01-17": "WC Mono Race (Altenberg)",
  "2026-01-18": "WC Two Woman Race (Altenberg)",
  "2026-01-19": "Sprint Maintenence: Heel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\nA-Skip 1x2 20m \nA-Switch 1x2 20m \nDouble Switch 1x4\nPush Specific ISO 3x5s ea.\nAccels 1x3 10m \nAccels 1x3 20m",
  "2026-01-20": "Strength work Eric: Oscillatory Back Squat 6x2 70lbs\nStanding Squat Drop Jump 6x3\nRDL Drop Catch 4x5\nOverhead Press 4x5",
  "2026-01-21": "Reactive Force:\nMobility Drills 1 Set\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x6\nDeep Tier Gorilla Leaps 2x6\nDeep Tier Split Squat Oscillations 4x12\nDeep Tier Split Exchange Leaps 2x12",
  "2026-01-22": "Sprint Maintenance: \nHeel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\n\n-\n\nMobility Drills 1 Set Dribble Series 1x8 20m Scissor Bounds 1x3 20m Walk-In Sprints 1x5 40m",
  "2026-01-23": "Max Strength: Power Clean Complex 1 3x1 115lbs\nHang Power Clean 5x1 135,155, 170,205lbs\nDepth Jump 5x3\nSL Hamstring Catch 4x5 ea \nBanded Hip Flexion 4x8 ea\nEccentric Adductor Planks 3x5 ea",
  "2026-01-24": "Igls Girls Dinner",
  "2026-01-25": "Holding Camp: Rested",
  "2026-01-26": "Sprint Maintenence: Heel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\nA-Skip 1x2 20m \nA-Switch 1x2 20m \nDouble Switch 1x4\nPush Specific ISO 3x5s ea.\nSled Bag Accels 1x15 no additional weight\nAccels 1x5 20m",
  "2026-01-27": "Movement: Hip ISO Push 4x5 secs ea\nSL KB Swing 4x5 ea\nEccentric Hip Flexor Sit-Up 4x5 ea\nEccentric Adductor Planks 4x5 ea",
  "2026-01-28": "Reactive Force:\nMobility Drills 1 Set\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x6\nDeep Tier Gorilla Leaps 2x6\nDeep Tier Split Squat Oscillations 4x12\nDeep Tier Split Exchange Leaps 2x12",
  "2026-01-29": "Sprint Maintenance: \nHeel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\n\n-\n\nMobility Drills 1 Set Dribble Series 1x8 20m Scissor Bounds 1x3 20m Walk-In Sprints 1x5 40m",
  "2026-01-30": "Joint care: Hip ISO Push 4x5 secs ea\nElevated Switches 4x5\nSL Hamstring Catch 4x5 ea\nBanded Hip Flexion 4x8 ea\nEccentric Adductor Planks 3x5 ea",
  "2026-01-31": "Off Sauna",
  "2026-02-01": "Arrive in Cortina",
  "2026-02-02": "Sprint Maintenence: Heel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\nA-Skip 1x2 20m \nA-Switch 1x2 20m \nDouble Switch 1x4\nPush Specific ISO 3x5s ea.\nSled Bag Accels 1x15 no additional weight\nAccels 1x5 20m",
  "2026-02-03": "Movement: Hip ISO Push 4x5 secs ea\nSL KB Swing 4x5 ea\nEccentric Hip Flexor Sit-Up 4x5 ea\nEccentric Adductor Planks 4x5 ea",
  "2026-02-04": "Reactive Force:\nMobility Drills 1 Set\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x6\nDeep Tier Gorilla Leaps 2x6\nDeep Tier Split Squat Oscillations 4x12\nDeep Tier Split Exchange Leaps 2x12",
  "2026-02-05": "Sprint Maintenance: \nHeel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\n\n-\n\nMobility Drills 1 Set Dribble Series 1x8 20m Scissor Bounds 1x3 20m Walk-In Sprints 1x5 40m",
  "2026-02-06": "Joint care: Hip ISO Push 4x5 secs ea\nElevated Switches 4x5\nSL Hamstring Catch 4x5 ea\nBanded Hip Flexion 4x8 ea\nEccentric Adductor Planks 3x5 ea",
  "2026-02-07": "Cortina Sliding",
  "2026-02-09": "Movemenet Prep: Hip ISO Push 4x5 secs ea\nElevated Switches 4x5\nSL Hamstring Catch 4x5 ea\nBanded Hip Flexion 4x8 ea\nEccentric Adductor Planks 3x5 ea",
  "2026-02-10": "Lower body tendon health: DB Bulgarian Split Squats 3x3 ea 1010 44,57,66lbs\nDB Bulgarian Split Squats 3x2 ea 6000 130lbs\nRear Foot Elevated Jumps 3x3 \nNordic Hamstring Curl 3x3\nBench Press 3x2 6000 132lbs\nEccentric Hip Flexor Sit-Up 3x5 ea\nEccentric Adductor Planks 3x5 ea\nPull-Up 3x4",
  "2026-02-11": "Coordination Spring: Mobility Drills 1 set\nA-Switch 2 sets\nPower Skips 4 sets 20m \nSkips for Distance 2 sets 30, \nGalloping Complete 4 sets\n30m - 2x each side\nFree Sprints 5 sets 60m - preferably barefoot on grass/ softer surface 75%",
  "2026-02-12": "Sprint Capacity: Mobility Drills 1 set\nDL Pogo Jump 2 x 20\nLateral Pogo Jumps 2 x 20\nDL Pogo w/ intermediate jump 2 x 20\nShin Dribbles 2 sets 30m \nKnee Dribbles 2 sets 30m \nDribble Bleed 3 sets 30m \nWalk-In Sprints 2 x 3 40m",
  "2026-02-13": "Joint Care: Eccentric Step-Down 4 x 8 44lbs\nRussian Twist 4 x 16\nDB Bench Press 4 x 8 44-66lbs\nRomanian Deadlift (RDL) 4 x 8 ea. 122-135lbs 6000 tempo\nCopenhagen Sideplank 4 x 20 secs ea.\nDB SL Row 4 x 8 ea. 35lbs-40lbs\nSupine Hip Flexion Cable 3 x 8 ea.\nSL Leg Curl Prone 3 x 8 ea. added some slow FS to the box",
  "2026-02-14": "Spa day (Fran)",
  "2026-02-15": "Womens Mono (Olympics) fran came",
  "2026-02-16": "Womens Mono (Olympics) GOLD MEDAL",
  "2026-02-17": "Lower body tendon health: DB Bulgarian Split Squats 3x3 ea 1010 44,57,66lbs\nDB Bulgarian Split Squats 3x2 ea 6000 130lbs\nRear Foot Elevated Jumps 3x3 \nNordic Hamstring Curl 3x3\nBench Press 3x2 6000 132lbs\nEccentric Hip Flexor Sit-Up 3x5 ea\nEccentric Adductor Planks 3x5 ea\nPull-Up 3x4",
  "2026-02-18": "Coordination Spring: Mobility Drills 1 set\nA-Switch 2 sets\nPower Skips 4 sets 20m \nSkips for Distance 2 sets 30, \nGalloping Complete 4 sets\n30m - 2x each side\nFree Sprints 5 sets 60m - preferably barefoot on grass/ softer surface 75%",
  "2026-02-19": "Sprint Capacity: Mobility Drills 1 set\nDL Pogo Jump 2 x 20\nLateral Pogo Jumps 2 x 20\nDL Pogo w/ intermediate jump 2 x 20\nShin Dribbles 2 sets 30m \nKnee Dribbles 2 sets 30m \nDribble Bleed 3 sets 30m \nWalk-In Sprints 2 x 4 40m",
  "2026-02-20": "Two Woman (Olympics) Joint Care: Eccentric Step-Down 4 x 8 44lbs\nRussian Twist 4 x 16\nDB Bench Press 4 x 8 44-66lbs\nRomanian Deadlift (RDL) 4 x 8 ea. 122-135lbs 6000 tempo\nCopenhagen Sideplank 4 x 20 secs ea.\nDB SL Row 4 x 8 ea. 35lbs-40lbs\nSupine Hip Flexion Cable 3 x 8 ea.\nSL Leg Curl Prone 3 x 8 ea. added some slow FS to the box",
  "2026-02-21": "Two Woman (Olympics) 7th",
  "2026-02-22": "Fran picked me up (drove to Bolzano)",
  "2026-02-23": "Bolzano (hotel) Sprint acceleration: Bolzano track, hurdles, banded bounds: Deep Tier Oscillations 2 x 12\nDeep Tier 2Fwd 1Bwd 2 x 12\nDeep Tier Split Squat Oscillations 2 x 12\nAccel Pyramid 2 sets Rest: 15sec per 5m\nTechnical Focus - 10m, 15m, 20m, 30m, 40m, 40m,  30m, 20m, 15m, 10m / Rest: 15sec per 5m",
  "2026-02-24": "Bolzano gym: Max Strength Back Squat 3 x 6, 4, 2 135,220,240lbs\nIsometric Hold Back Squat 4 x 3 76% (177lbs) hold 5 sec at bottom\nRear Foot Elevated Jumps 4 x 3\nRomanian Deadlift (RDL) 3 x 4 0500 tempo 135lbs\nBench Press 3 x 3 0500 90lbs\nEccentric Hip Flexor Sit-Up 3 x 5 ea.\nEccentric Adductor Planks 3 x 5 ea.",
  "2026-02-25": "Coordination Spring: Mobility Drills 1 set\nA-Switch 2 sets\nPower Skips 4 sets 20m \nSkips for Distance 2 sets 30, \nGalloping Complete 4 sets\n30m - 2x each side\nFree Sprints 5 sets 60m - preferably barefoot on grass/ softer surface 75%",
  "2026-02-26": "Sprint Capacity: Mobility Drills 1 set\nDL Pogo Jump 2 x 20\nLateral Pogo Jumps 2 x 20\nDL Pogo w/ intermediate jump 2 x 20\nShin Dribbles 2 sets 30m \nKnee Dribbles 2 sets 30m \nDribble Bleed 3 sets 30m \nWalk-In Sprints 2 x 4 40m",
  "2026-02-27": "Joint Strength: Isometric Hold Bulgarian Split Squat 4 x 8 0500 tempo 88lbs\nRussian Twist 4 x 16 \nDB Bench Press 4 x 8 44lbs\nRomanian Deadlift (RDL) 4 x 8 ea. 0500 tempo125lbs \nCopenhagen Sideplank 4 x 20 secs ea.\nDB SL Row 4 x 8 ea. \nSupine Hip Flexion Cable 3 x 8 ea.\nSL Leg Curl Prone 3 x 8 ea.",
  "2026-02-28": "Beach Training (dribbles and drills with Fran) longer runs and banded dribbles",
  "2026-03-04": "Strength Capacity: Sled pull backwards 4x20m heavy, Sled Heavy Stomps 4x15m,  Back Squat 3x6,4,2 (148,207236lbs)\nBack Squat 4x3 (241,251,257,257lbs)\nSinlge Broadjumps 4x3 + Drop jump\nRomanian Deadlift (RDL) 4x3 tempo 0500\nBench Press 4x3 0500\nEccentric Hip Flexor Sit-Up 3x5 ea\nEccentric Adductor Planks 3x5 ea\nPull-Up 3x6 (adductors and abductors) Travel- Spain - Brussles Strength Capacity",
  "2026-03-05": "Field Park work: Free Sprints: Mobility Drills (Brussles)\nA-Switch 2 sets b\nPower Skips 4 sets 20m \nSkips for Distance 2 sets 30, \nGalloping Complete 4 sets\n30m - 2x each side\nFree Sprints 5 sets 60m - preferably barefoot on grass/ softer surface 75%-\nPM: Movements Health\nHip Cars (rollers)\nSingle Leg Bulgarian Twist \nBroad jumps banded + broad jumps 3+3x\nSingle Arm banded Rows 3x8\nTspin Holds 3x30sec\nRudiment hops 4x40reps Lateral Hops on step 5x20m\nFarmer Carry banded 3x20m\n45 Degree Side Crunch off bench",
  "2026-03-06": "Travel to Brussles -Budapest- Venice (exhasued from 2 weeks average) moved around in parking lot for 20 mins easy warm up",
  "2026-03-07": "Sprint Capacity: Travel- Venice to Malta (Long warm up from Dominic and banded drills added 6x 25m banded boudning + skips",
  "2026-03-09": "Sled accels: Mobility Drills 1 Set (Malta Streets)\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x12\nDeep Tier Split Squat Oscillations 2x12\nDeep Tier Double Dip Split Stance Leaps 4x12\nSled Pull 2x5 (50% BW with abnd 77lbs)\nAccels 1x4 (overspeed down hill)",
  "2026-03-10": "Free Sprints: Mobility Drills 1 set\nA-Switch 2 sets b\nPower Skips 4 sets 20m \nSkips for Distance 2 sets 30, \nGalloping Complete 4 sets\n30m - 2x each side\nFree Sprints 5 sets 60m - preferably barefoot on grass/ softer surface 75%\n\nPush press 4x3 132lbs\nDB bench SA 4x8 33lbs + Tempo Bench 4x3 0500 (110lbs)\nBroad jumps 3x3\nContinuous hops \nT spine hold 3x45 15kg \nOpposite Chinese plank 3x45 10kg\nSide beds 3x20\nSling core 3x20 + hanging core 500reps",
  "2026-03-11": "Strength + Pushing: Sled pull backwards 4x20m heavy, Sled Heavy Stomps 4x15m, Sled Banded Resisted 2x4 + Sled Fast Pushes 2x4, Back Squat 3x6,4,2 (148,207236lbs)\nBack Squat 4x3 (241,251,257,257lbs)\nSinlge Broadjumps 4x3 + Drop jump\nRomanian Deadlift (RDL) 4x3 \nSL DB Hip Thrust 4x3\nEccentric Hip Flexor Sit-Up 3x5 ea\nEccentric Adductor Planks 3x5 ea\nPull-Up 3x6 + (adductors and abductors)",
  "2026-03-12": "Malta Sprint Positons on Beach close to airport\nHeel scoops 20m \nKnee Pulls 20m \nBack leg pull to kick back 20m \nReverse lunge twists 20m \nReverse Lunge side windmill 20m \nWorlds greatest stretch 20m \nSide lunge to turn 20m\n\nMobility Drills 1 Set DL Pogo Jump 2x20 Lateral Pogo Jumps 2x20 DL Pogo w/ Intermediate Jump 2x20\nShin Dribbles 2 Sets 20m ROM Resisted Dribbles 5 Sets 20m light resistance  Dribble Bleed 2 Sets 30m\nWalk-In Sprints 3x3 40m 120 secs90 % (300sec after rest)",
  "2026-03-13": "Rest Istanbul",
  "2026-03-14": "Rest Shake Out",
  "2026-03-15": "Strength: In Istanbul Bulgarian Split Squat 4x8 tempo\nRussian Twist 4x16\nDB Bench Press 4x8\n\nSL DB Hip Thrust 4x8 ea\nCopenhagen Sideplank 4x20s ea\nDB SL Row 4x8 ea\n\nSupine Hip Flexion Cable 3x8 ea\nSL Leg Curl Prone 3x8 eaIstanbul",
  "2026-03-16": "Travel (Shakeout) Cappadocia Mobility Drills 1 Set (Malta Streets)\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x12\nDeep Tier Split Squat Oscillations 2x12\nDeep Tier Double Dip Split Stance Leaps 4x12\nISO in Airbnb",
  "2026-03-17": "Hill Sprints: 75% Mobility Drills 1 set\nA-Switch 2 sets b\nPower Skips 4 sets 20m \nSkips for Distance 2 sets 30, \nGalloping Complete 4 sets\nHills 50m 10x every 30sec @ 75%\nWalked 7.5 miles around the city (post travel really exhausted) not getting enough sleep work stress high",
  "2026-03-18": "Strength Cappadocia Capacity (Lower Body) BRIDGE\nKeiser Leg Press (Velocity Ramp) 5 progressive sets (40–80%)\nBack Squat 9x2 @ 245 lbs (76%)\nSingle-Leg RDL (Barbell) @110-85lbs\nGHD Sit-Up 18lbs\nSkater Squat 3x8 ea 20lb\nLeg Curl Cable 3x8 ea (34lbs)\nCalf Raises Machine 2x15 (90lbs) \nChinese High Pul 3x20e 15-10kg\nMilitary BB Seated Press 3x3 65lbs\nSeal Row 3x6 115lbs \nAdductors Abductor 3x20 failure\nHanging Leg Raises 3x40 reps \n-\nAM hiked Gore mushroom mountains\nWalked 10.5 miles",
  "2026-03-19": "Speed Capacity: Cappadocia Sand Mobility Drills 1 set\nDL Pogo Jump 2x20\nLateral Pogo Jumps 2x20\nDL Pogo w/ Intermediate Jump 2x20\nShin Dribbles 2 sets 20m \nResisted Dribbles 5 sets 20m \nDribble Bleed 2 sets 30m \nWalk-In Sprints 3x3 120 secs\n90 % 40m",
  "2026-03-20": "Airport: Istanbul-Vienna-Venice\nFree Sprints: Mobility Drills 1 set\nA skip 3x20m \nSingle single switch bound 2x30m\nDL Pogo Jump 2x20\nLateral Pogo Jumps 2x20\nDL Pogo w/ Intermediate Jump \nCircuit: \nSumo jump squats 20x\nJump lunge alternate 20x \nPogo lateral 40x\n3x \nPush-ups bench 3x20\nDips 2x15\nCore 100 reps \n-\nAnimal flow 10mins",
  "2026-03-21": "Strength Maron Capacity (Lower Body – Hinge Focus) Feelinf run down \nLeg Curl (Velocity Ramp) 5 progressive sets (40–80%)\nDeadlift (Barbell) 9x2 @ 220 lbs (76%)\nFront-Foot Elevated Reverse Lunge (Barbell) 4x6 ea (last set to 0 RIR)\nKettlebell Windmill (SL Leg) 3x8 ea\nLeg Extension 4x8 \nLeg Curl 4x8 \nCalf Raise 4x8 \nLower Limb Touch-Up\nForward Lean Calf Raise (WALL) 2x10 ea",
  "2026-03-22": "Speed Bag Contrast (feeling run down throat) Italy (seaside)\n-\nAM\nMobility Drills 1 set\nShin Dribbles 2 sets 20m \nResisted Dribbles 5 sets 20m \nDribble Bleed 2 sets 30m \n-\nHill Plyometrics 3x30 contacts each Single-leg hops forward backward lateral Double-leg hops forward and backward Mini bounds\n-\nAcceleration Build-Up 2x40m @ 100% 7 min rest\nSpeed Circuit (2 rounds) Sled pull 30 lb x 30m Rest 2 min Bounding 30m Rest 2 min Sprint 30m Rest 10 min between rounds\n2x\n-\nAccessories \nToe Arcs 2x10 ea\nBig Toe vs Other Toes 2x10 ea\n\nPM- BJJ Drills with Francesco on the beach",
  "2026-03-23": "BRIDGE 1/2 Short Strength Session: (starting to feel run down) Italy (Marone)\nChest Press 6x3 @132lbs fast \nFast Concentric Row 5x2 @66lbs (Pull-Up, Neutral Grip) 7x3 @6lbs\nUpper Accessories\nZ Press 4x6 @45lbs BJJ Banded Lunge Switch 4x6/e side L-Raise on Bench 3x8  Dips – Bodyweight 3x6-8",
  "2026-03-24": "Sick Easy Shakeout: Italy (Bolzano)  Full warmup sprints, 2x4 60m 60% run 10sec rest 30sec 2x plyo banded",
  "2026-03-25": "Sprints: Hills 2x6 40m, 2x40m accles BRIDGE Strength: Italy (Bolzano)  Keiser Leg Press – Concentric (or pin squats)  5x1, 40–80% 1RME, Rest 00:10 (230–460 lbs) \nBack Squat 6x4, 74% 1RME, OT 1:45 @235 lbs\nPosterior Chain / Core RDL – Barbell, Single Leg Banded: 4x7 ea, RIR 0–2 GHD Situp: 3x10, RIR 1–2\nLower Body Accessories Skater Squat: 3x10, RIR 1–2 Leg Curl – Roller: 3x10 ea, RIR 1–2 Calf Raises – Keiser Leg Press: 2x20, RIR 1\nEccentric Hip Flexor Sit-Up 3x5 ea Hip Pistons – Feet on Wall: 2x10 ea 1/2 Kneeling Knee Lift to Plate: 2x10 ea Hip Flexion – Seated Straight Leg Raise: 2x10 ea",
  "2026-03-26": "Track Sled accels: Mobility Drills 1 Set (Malta Streets)\nDeep Tier Oscillations 2x12\nDeep Tier 2Fwd 1Bwd 2x12\nDeep Tier Split Squat Oscillations 2x12\nDeep Tier Double Dip Split Stance Leaps 4x12 Set DL Pogo Jump 2x20 Lateral Pogo Jumps 2x20 DL Pogo w/ Intermediate Jump 2x20\nShin Dribbles 2 Sets 20m ROM Resisted Dribbles 5 Sets 20m light resistance  Dribble Bleed 2 Sets 30m\nWalk-In Sprints 3x3 40m 120 secs90 % (300sec after rest)\nSled Pull 2x5 (50% BW with abnd 77lbs)\nAccels 1x4 (overspeed down hill) & hurdles",
  "2026-03-27": "BRIDGE: Strength\nLeg Curl (Velocity Ramp) 5 progressive sets (40–80%)\nDeadlift (Barbell) \n9x2 @ 220 lbs (76%)\nFront-Foot Elevated Reverse Lunge (Barbell) 4x6 ea (last set to 0 RIR)\nKettlebell Windmill (SL Leg) 3x8 ea\nLeg Extension 4x8 \nLeg Curl 4x8 \nCalf Raise 4x8 \nLower Limb Touch-Up\nForward Lean Calf Raise (WALL) 2x10 ea",
  "2026-03-28": "Conditioning CLT: 5x5, 82% (42m) —42sec— 85% (47m) —50sec— 92% (50m) 70sec— sprints @ 90–95% effort —2min 30sec rest— \nWalk back recovery 90–120 sec  (ball tosses)",
  "2026-03-29": "Rest Easy Day 7hr drive (shook out on beach hip mobility and 5x banded 20m skips and jumps)",
  "2026-03-30": "Speed and Sprint Development Session Hill Plyo Core\nAM\nLight Aerobics nasal breathing only 1 set\nDynamic Mobility Drills Walking Lunge 10 reps Inch Worms 5 reps Side Skip and Squat 10 reps R L Carioca 10 reps R L Skips Forward 10 reps Skips Back 10 reps Leg Swings front back 10 reps R L Leg Swings side to side 10 reps R L\nActivation Drills Power Skips 20m Wall Drill Push 10 reps R L Banded Hip Step 10 reps R L\n\nHill Sprint Contrast Block\nMax effort steep hill 10 to 15 degrees 10m 5 to 6 reps 120 sec rest 20m 5 to 6 reps 120 sec rest 30m 5 to 6 reps 120 sec rest\nREST TIMER 180 sec between sets\n\nPlyometric Finisher optional\nJump uphill if no steps available\nDouble Foot Hops 3 to 5 jumps Single Foot Hops 3 to 5 jumps each leg Alternate Bounds 3 to 6 jumps\n* 1-2 rounds\nCore Circuit 1 to 2 rounds\nV Situps 10 reps Leg Toss 10 reps Crunch with Twist 10 reps Prone Flexed Knee Hip Extension 10 reps R L Toe Touchers 10 reps Window Wipers 10 reps Side Ups 10 reps R L Double Leg Eagles 10 reps Low Level Bicycle 10 reps Pelvic Tilt Isometrics 10 reps Pelvic Tilt with Leg Crunch 10 reps",
  "2026-03-31": "Strength Bolzano: Spinal Mobility A\nKnee Hug Rolls x10 Inverted Scissors x10 Cobras x10 Crucifix x10 Scorpions x10 Cat Tail – 10 deep breaths (each side) Lat Stretch – 30s–1 min\n\nHip Mobility A\nHip Extension Glides x10 (each side) Windscreen Wipers x10 Windscreen Wipers (Hands Free) x10 Alternate Pigeon Pose x10\n\nStrength Lift Work\nFront Squat 3 x 5 (3-1-0) @ 8 RPE 3-1-0 tempo @165lbs Hyperextension with Row 3 x 8 @ 8 RPE Incline DB Press 3 x 10 @ 8 RPE 44lbs Hanging Frog Raises 3 x 10 Hamstring ISO Hold 2 x 30 sec (each side) Seated Calf Raise 3 x 8",
  "2026-04-01": "TEMPOS: Warm-Up & Drills\nComplete 2 Rounds\nStanding A Skip x10 (L/R) Standing B Skip x10 (L/R) A-Skip x20m B-Skip x20m A Switches x20m Triples x20m\nArm Mechanics Drill\nComplete 1 Set\n2 reps x 20m (left arm overhead)\n\nTempo Runs\n60m x 8 @ 70–85%\n* 70% → 10.93s\n* 75% → 10.20s\n* 80% → 9.56s\n* 85% → 9.00s\n\nVerdun Circuit\nComplete 1 Round (20 yards each)\nLow Walks (Forward) Low Walks (Backward) Duck Lunge Walks Lateral Duck Walks Lunge Extension Walks Low Walks (Lateral) Duck Walk\n\n3D Core Circuit ISO hamstrings\nRound 1 – Elbow Stand\nStraight Leg Back x10 (L/R) Straight Leg Front x10 (L/R) Straight Leg Side x10 (L/R) Straight Leg Medial x10 (L/R) Bent Leg Back x10 (L/R) Bent Leg Front x10 (L/R) Straight Leg Side Kick x10 (L/R)\n\nRound 2 – Hand Stand\nStraight Leg Back x10 (L/R) Straight Leg Front x10 (L/R) Straight Leg Side x10 (L/R) Straight Leg Medial x10 (L/R) Bent Leg Back x10 (L/R) Bent Leg Front x10 (L/R) Knee Raise Side x10 (L/R)\n\nRound 3 – Abs\nSide Crunches x30 CrossFit Sit-Ups x20\n* Right leg lead\n* Left leg lead\n* Forward (1 step each) \n* Backward (1 step each)\nHigh Knee Side Skip (L/R) Straight Leg Side Skip (L/R) Over Unders\n\nMARONE TRACK LATER: \nAfter drive shake out\nHurdles 15mins 300 reps all \nHurdles 2 double bounce to 2 high jumps\nPatter dribble drills \nSled drags resisted with bands 3x30m",
  "2026-04-02": "Strength MORONE: Spinal Mobility A\nKnee Hug Rolls x10 Inverted Scissors x10 Cobras x10 Crucifix x10 Scorpions x10 Cat Tail – 10 deep breaths (L/R) Lat Stretch – 30s–1 min\n\nHip Mobility A\nHip Extension Glides x10 (L/R) Windscreen Wipers x10 Windscreen Wipers (Hands Free) x10 Alternate Pigeon Pose x10\n\nPlyometric / Power\nMB Seated Box Jump 3 x 6 5kg Clean Pull 3 x 5 → + MB Toss to Jump (BOBSTART)\n\nStrength Lift Work\nStep-Up w/ Hip Lock 3 x 5 (each side) 132lbs Chin-Ups 3 x AMAP Kneeling Landmine Twist 3 x 10 45lbs empty bar Psoas Bench Rock Back 3 x 9 (each side) right side reach left side reach back \n\nBridge / Supplemental Power\nStaggered Leg Press (Heavy, Fast) 5 x 3 (each side) Power Cleans (Fast) 2 x 3 Single-Leg Skater Deadlift 3 x 6 (each side) Sprinter Leg Pushdowns 3 x 6 (each side) Skater Squat 3 x 8 (each side, ~30 lbs) Half-Kneeling Knee Lift to Plate 3 x 3 (each side)",
  "2026-04-03": "HILL: Warm-Up & Movement Prep\nLight Aerobics (nasal breathing only) – 5 min\nWalking Lunges x10 Inchworms x5 Side Skip + Squat x10 (L/R) Carioca x10 (L/R) Skips Forward x10 Skips Backward x10\nLeg Swings (front/back) x10 (L/R) Leg Swings (side-to-side) x10 (L/R)\n\nSprint Prep\nPower Skips x20m Wall Drill Push x10 (L/R) Banded Hip Steps x10 (L/R)\n\nSprint Work\nMaximal Sprint – Hill (10–15° incline)\n\nTechnical Work\nThrows: 5–6 reps each\n\nMedicine Ball Power Circuit\nComplete 1 Round (4–6 kg MB)\nOH Backward Toss x5–6 Between Legs Forward Toss x5–6 Chest Pass Forward x5–6 Sprint Start Toss x5–6 (L/R) Side Sling x5–6 (L/R)\nCore Work\nMB Core Series 1 (Optional)\nComplete 1 Round (4–6 kg MB, 10–20 reps each)\nOH Lateral Reach x10–20 OH Straddle x10–20 Alternate Toe Touchers x10–20 Hip Bridge Lateral Reach x10–20 Seated Russian Twist x10–20",
  "2026-04-04": "Vipetano Italy Strength: \nMB Warm-Up\n1–2 Sets – 10 reps each (barefoot)\nForward Lunge + Twist x10 Backward Lunge x10 Side Skip + Squat x10 (L/R) Hop + Toe Touch x10\n\nStrength & Power\nDeficit KB High Pull 2 x 15 43lbs Hip ISO Hold (Test) 1 x ALAP (each side) 3mins each side Spring Ankle 1 2 x 30–45s (each side)Main Strength 132lbs\nElevated Reverse Lunge 4 x 6 (each side) 122,142,142,153 Inverted Row 4 x 10–12 feet on box 3 weighted and 3 fast bodyweight \n\nAccessory Block\nA. Copenhagen ISO Hold 2 x 30–45s (each side)\nB. 1/2 Starfish Side Kick 2 x 30–45s (each side)\n\nEXTRA accessories from BRDIGE: \nKB Windmill (OFF BENCH)\nLeg Extension 4x10 \nLeg Press Calf Fast 4x10\nISO Adductor Hold 3x30sec \nToe Arcs x10 (each) x2 Big Toe vs Other Toes x10 (each) x2",
  "2026-04-05": "Drove to Austria 3.5hrs (activation)",
  "2026-04-06": "Austria Push Track: Warm-Up A\nLight Aerobics (nasal breathing only) 1x5min\nWalking Lunge 1x10 Inchworms 1x5 Side Skip + Squat 1x10 each side Carioca 1x10 each side Skips Forward 1x10 Skips Backward 1x10 Leg Swings Front/Back 1x10 each Leg Swings Side/Side 1x10 each\n\nAcceleration 1\nPower Skips 1x20m Wall Drill Push 1x10 each Banded Hip Step 1x10 each\n\nDrop-In Sprint\n1x2–3\n\nPush Track\n1x6 3 reps to 15m, 3 reps to 25m\nI added (2x ISOs in drop hold positions) \nI added 3 extra reps to 30m focus on the low heels \n\nStair Plyo Series\n1xComplete 2 rounds\nDouble Foot Hops 3-5 Jumps\nSingle Foot Hops 3-5 Jumps\nAlternate Bounds 3-6 Jumps\n\nPillar Core / (added some at gym) Innsbruck \nAcessories: \nSled drap backwards 30m 4x \nChest cable press fast 4x6 \nStability./ Knee \nRDL Balance Board with Row 3x8/e \nHigh Single Leg Box Squat 3x6/e\nCore: \nSB Ball crunches 2x13\nHanging Side Swings 2x50 \nLateral Sling Plank 2x45sec\nTall Kneeling Hip to Box rech 2x6/e\nSide Plank with Ball Hug turns on toes: 3x12/e",
  "2026-04-07": "Pushing hits: 7x 15m focused on the first step and low heel revocerySpinal Mobility A\nKnee Hug Rolls 1x10 Inverted Scissors 1x10 Cobras 1x10 Crucifix 1x10 Scorpions 1x10 Cat Tail 1x10 breaths each Lat Stretch 1x30–60s\n\nHip Mobility A\nHip Extension Glides 1x10 each Windscreen Wipers 1x10 Windscreen Wipers (hands free) 1x10 Alternate Pigeon Pose 1x10\n\nStrength\nFront Squat 3x5 @3-0-1 (132lbs) Hyperextension with Row (55lbs) 3x8 Incline DB Press (40kg) 3x10\nSkater Squat (10lbs) 3x10 Hanging Frog Raises 200reps 3x10 Hip Hamstring ISO 2x30s each Seated Calf Raise 3x8",
  "2026-04-08": "Austria Push track \nComplete 2 Rounds\nStanding A Skip x10 (L/R) Standing B Skip x10 (L/R) A-Skip x20m B-Skip x20m A Switches x20m Triples x20m\nBanded double step start drill\n1 arm overhead straight leg bound\n2 reps x 20m (left arm overhead)\nISOS on bobsled \n3 positions 2x 7 sec hard activating quad and ankle \n\nTempo Pushing\n60m 2 x 4  @ 70–85%\n* 70% → 35m\n* 75% → 40m\n* 80% → 44m\n* 85% → 44m\n—-2 mins after each— \n—— 5 mins rest——\n* 80% → 35m\n* 80% → 40m\n* 75% → 44m with Fran \n* 85% → 44m with Fran \n—3mins after each—\n\nVerdun Circuit\nComplete 1 Round (20 yards each)\nLow Walks (Forward) Low Walks (Backward) Duck Lunge Walks Lateral Duck Walks Lunge Extension Walks Low Walks (Lateral) Duck Walk\n\n3D Core Circuit ISO hamstrings\nRound 1 – Elbow Stand\nStraight Leg Back x10 (L/R) Straight Leg Front x10 (L/R) Straight Leg Side x10 (L/R) Straight Leg Medial x10 (L/R) Bent Leg Back x10 (L/R) Bent Leg Front x10 (L/R) Straight Leg Side Kick x10 (L/R)\n\nRound 2 – Hand Stand\nStraight Leg Back x10 (L/R) Straight Leg Front x10 (L/R) Straight Leg Side x10 (L/R) Straight Leg Medial x10 (L/R) Bent Leg Back x10 (L/R) Bent Leg Front x10 (L/R) Knee Raise Side x10 (L/R)\n\nRound 3 – Abs\nSide Crunches x30 CrossFit Sit-Ups x20\n* Right leg lead\n* Left leg lead\n* Forward (1 step each) \n* Backward (1 step each)\nHigh Knee Side Skip (L/R) Straight Leg Side Skip (L/R) Over Unders\n\nBM Care with Fran \n1 x side MB tosses 15x each side \n1 x flutter kick BTH MB toss 15x \n1 x seated later MB toss bike 10x \n2 x supine flutter kicks MB drop to toss 20x",
  "2026-04-09": "Strength MORONE: Spinal Mobility (tall kneeling MB turns) \nDynamic warm up\nHip Extension Glides x10 (L/R)\nPulse squats and lunges \n4 x seated on shin to 2x broad jump increasing distance \n\nPlyometric / Power\nMB Seated Box Jump 3 x 6 5kg Clean Pull 3 x 5 (100-115kg) → + MB Depth Drop to Box Jump 3R\n\nStrength Lift Work\nStep-Up w/ Hip Lock 3 x 5 (each side) 132lbs Chin-Ups 3 x AMAP 9 reps Kneeling Landmine Twist 3 x 10 45lbs empty bar Psoas Bench Rock Back 3 x 9 (each side) right side reach left side reach back",
  "2026-04-10": "CNS REFRESH Day: Hurdles and Sandpit foot care ISOS",
  "2026-04-11": "Marone Italy (sluggish menstral) MB Warm-Up\n1–2 Sets – 10 reps each (barefoot)\nForward Lunge + Twist x10 Backward Lunge x10 Side Skip + Squat x10 (L/R) Hop + Toe Touch x10\n\nStrength & Power\nDeficit KB High Pull 2 x 15 43lbs Hip ISO Hold (Test) 1 x ALAP (each side) 3.40sec mins each side Spring Ankle 1 2 x 30–45s (each side)\nElevated Reverse Lunge 4 x 6 (each side) 122,  Row 4 x 8 reps speedy 110lbs\n\nAccessory Block\nA. Copenhagen ISO Hold 2 x 30–45s (each side)\nB. 1/2 Starfish Side Kick 2 x 30–45s (each side)",
  "2026-04-12": "Pushing hit 2 step crest focused 5x 20m — longer warm up 3x ISOS bobsled positions focused on pressure through hands, banded knee exterminators, banded knee toe iso 2x20sec, hills 3x15m build ins, A in place, B in place, A skip 20m, B skip 20m, Switches 20m",
  "2026-04-13": "Pushing 8x 15m uphill maximal knee throug, 4x 15m on the flat: Pillar Core / (added some at gym) Innsbruck \nAcessories: \nSled drap backwards 30m 4x \nChest cable press fast 4x6 \nStability./ Knee \nRDL Balance Board with Row 3x8/e \nHigh Single Leg Box Squat 3x6/e\nCore: \nSB Ball crunches 2x13\nHanging Side Swings 2x50 \nLateral Sling Plank 2x45sec\nTall Kneeling Hip to Box rech 2x6/e\nSide Plank with Ball Hug turns on toes: 3x12/e",
  "2026-04-14": "Pushing hits: 6x30m focused on the first step and low heel revocerySpinal Mobility A\nKnee Hug Rolls 1x10 Inverted Scissors 1x10 Cobras 1x10 Crucifix 1x10 Scorpions 1x10 Cat Tail 1x10 breaths each Lat Stretch 1x30–60s\n\nHip Mobility A\nHip Extension Glides 1x10 each Windscreen Wipers 1x10 Windscreen Wipers (hands free) 1x10 Alternate Pigeon Pose 1x10\n\nStrength\nFront Squat 3x5 @3-0-1 (132lbs) Hyperextension with Row (55lbs) 3x8 ISOS hips video  Incline DB Press (40kg) 3x10\nSkater Squat (10lbs) 3x10 Hanging Frog Raises 200reps 3x10 Hip Hamstring ISO 2x30s each Seated Calf Raise 3x8",
  "2026-04-15": "Bolzano, Italy \nHip Extension Glides x10 (L/R)\nPulse squats and lunges + seated shin brod jumps\n4 x seated on shin to 2x broad jump increasing distance \n\nPlyometric / Power\nMB Seated Box Jump 3 x 6 5kg Clean Pull 3 x 5 (100-115kg) → + MB Depth Drop to Box Jump 3R\n\nStrength Lift Work\nStep-Up w/ Hip Lock 3 x 5 (each side) 132lbs Chin-Ups 3 x AMAP 9 reps Kneeling Landmine Twist 3 x 10 45lbs empty bar Psoas Bench Rock Back 3 x 9 (each side) right side reach left side reach back \"hanging core 300 reps",
  "2026-04-16": "Bolzano, Italy (needed to take a few days off from burn out)",
  "2026-04-17": "Marone, Italy (needed to take a few days off from burn out)",
  "2026-04-18": "Solvania, Portorož (needed to take a few days off from burn out)",
  "2026-04-19": "Solvania, Portorož (needed to take a few days off from burn out)",
  "2026-04-20": "Marone, Italy Tempo  Warm-Up & Drills\nComplete 2 Rounds\nStanding A Skip x10 (L/R) Standing B Skip x10 (L/R) A-Skip x20m B-Skip x20m A Switches x20m Triples x20m\nArm Mechanics Drill\nComplete 1 Set\n2 reps x 20m (left arm overhead)\n\nTempo Runs\n60m x 10 @ 70–85%\n* 70% → 10.93s\n* 75% → 10.20s\n* 80% → 9.56s\n* 85% → 9.20s\n* 85% → 9.20s\n* 85% → 9.20s\n* 85% → 9.20s\n* 85% → 9.20s\n* 85% → 9.20s\n* 85% → 9.80s\n\n3D Core Circuit ISO hamstrings 2x through \nRound 1 – Elbow Stand\nStraight Leg Back x10 (L/R) Straight Leg Front x10 (L/R) Straight Leg Side x10 (L/R) Straight Leg Medial x10 (L/R) Bent Leg Back x10 (L/R) Bent Leg Front x10 (L/R) Straight Leg Side Kick x10 (L/R)\n\nRound 2 – Hand Stand\nStraight Leg Back x10 (L/R) Straight Leg Front x10 (L/R) Straight Leg Side x10 (L/R) Straight Leg Medial x10 (L/R) Bent Leg Back x10 (L/R) Bent Leg Front x10 (L/R) Knee Raise Side x10 (L/R)\n\nRound 3 – Abs 500 reps \nSide Crunches x30 CrossFit Sit-Ups x20\n* Right leg lead\n* Left leg lead\n* Forward (1 step each) \n* Backward (1 step each)\nHigh Knee Side Skip (L/R) Straight Leg Side Skip (L/R) Over Unders\n\nVerdun Circuit\nComplete 1 Round (20 yards each)\nLow Walks (Forward) Low Walks (Backward) Duck Lunge Walks Lateral Duck Walks Lunge Extension Walks Low Walks (Lateral) Duck Walk Mood notes: on track felt great and made all intervalts",
  "2026-04-21": "Pushing, Innsbruck: Warm-Up A\n\nLight Aerobics (nasal breathing only) x5 min\nWalking Lunge x10\nInch Worms x5\nSide Skip + Squat x10 (R/L)\nCarioca x10 (R/L)\nSkips Forward x10\nSkips Backward x10\nLeg Swings (front/back) x10 (R/L)\nLeg Swings (side-to-side) x10 (R/L)\n\nAcceleration Prep\n\nPower Skips x20m\nWall Drill Push x10 (R/L)\nBanded Hip Step x10 (R/L)\n\nDrop-In Sprints\n1 x 2–3 reps\n\nPush Track\n1 x 6 reps: 3 reps to 15m, 3 reps to 25m \n\nStair Plyo Series: Jump uphill if no steps are available \n\nComplete 2 rounds\nDouble Foot Hops 3-5 Jumps\nSingle Foot Hops 3-5 Jumps\nAlternate Bounds 3-6 Jumps\nPillar: Complete 1 round\n\nPM SESSION: Bolzano, Italy Strength- Spinal Mobility A\n\nHip Mobility A\nHip Extension Glides x10 (R/L)\nWindscreen Wipers x10\nWindscreen Wipers (hands free) x10\nAlternate Pigeon Pose x10\nFront Squat – 3 x 5 (8RPE 3-1-0 from pins 305lbs) * R knee irritated\nHyperextension with Row – 3 x 8 24kg\nIncline DB Press – 3 x 10 99lbs\nHanging Frog Raises – 3 x 10\nHamstring ISO Hold – 2 x 40s (each)\nSeated Calf Raise – 3 x 8",
  "2026-04-22": "Double: Pushing, Innsbruck : Warm-Up A\n\nLight Aerobics (nasal breathing only) x5 min\nWalking Lunge x10\nInch Worms x5\nSide Skip + Squat x10 (R/L)\nCarioca x10 (R/L)\nSkips Forward x10\nSkips Backward x10\nLeg Swings (front/back) x10 (R/L)\nLeg Swings (side-to-side) x10 (R/L)\n\nAcceleration Prep\n\nPower Skips x20m\nWall Drill Push x10 (R/L)\nBanded Hip Step x10 (R/L)\n\nHill Sprints\n1 x 5 (20m build ins) \nPush Track\n1 x 3 15m brake hits \nUp Hill Bobsled \n1 x 4 (torque pushes 15m) \n1 x 4 (torque pushes slow bound 15m) \n1 x 4 (torque pushes over sled 15m) \n1 x 2 (arms straight pushes 15m) \nHits on Bob: \n1 x 4 hit 10m (focus on flat feet and straight arms)",
  "2026-04-23": "Bolzano Italy: \nSpinal Mobility (tall kneeling MB turns) \nExplosive Throws Series 1\n5-6 throws each\n2R\n4-6kg Medicine Ball\n1. OH Backward\n2. Between Legs Forward\n3. Chest Toss Forward \n4. Sprint Start Toss L&R \n5. Side Sling L&R\n\nPlyometric / Power\nMB Seated Box Jump 3 x 6 5kg\nSeated BJ for max heightClean Pull 3 x 5 (100-115kg) → + MB Depth Drop to Box Jump 3R\nStep-Up w/ Hip Lock 3 x 5 (each side) 132lbs Chin-Ups 3 x AMAP 9 reps Kneeling Landmine Twist 3 x 10 45lbs empty bar Psoas Bench Rock Back 3 x 9 (each side) right side reach left side reach back",
  "2026-04-24": "Marone, Italy (Track 60m runs) then PM optional with time --- Spinal Mobility A\n\nreverse sled drag knee health and foot sand pit care, with hurdle",
  "2026-04-25": "Lignano, Italy: Rest day easy drills and ISO 1x",
  "2026-04-26": "Marone, Italy - Beach drills with hip swivel, hip circle walks, upper body shake out with Fancesco the drills were a burner for hip patterning",
  "2026-04-27": "(Cortina, Italy) Pushing drop in sprints 2x20m, 3x20m x3 up hill pushing on technique, 9x20m flat pushes with Alex consulting in Canada",
  "2026-04-28": "Milano, Italy (Spinal Mobility A\nKnee Hug Rolls x10\nInverted Scissors x10\nCobras x10\nCrucifix x10\nScorpions x10\nCat Tail 10 deep breaths (L R)\nLat Stretch 30s to 1 min\n\nHip Mobility A\nHip Extension Glides x10 (R L)\nWindscreen Wipers x10\nWindscreen Wipers Hands Free x10\nAlternate Pigeon Pose x10\n\nBanded Hip Patterning 2 x 6 each\nSeated Rocker Box Jump 2 x 5\nClean Pull 2 x 4 + Push press 4x4 \nWeighted Chin Up 2 x 4",
  "2026-04-29": "Reykjavíkivi, Iceland✈️ (Light Aerobics (nasal breathing only) x5 min\nWalking Lunge x10\nInch Worms x5\nSide Skip + Squat x10 (R/L)\nCarioca x10 (R/L)\nSkips Forward x10\nSkips Backward x10\nLeg Swings (front/back) x10 (R/L)\nLeg Swings (side-to-side) x10 (R/L)\n\nAcceleration Prep\n\nPower Skips x20m\nWall Drill Push x10 (R/L)\nBanded Hip Step x10 (R/L)\nDrop in sprints hill 2x5\nHill Sprints\n2 x 5 (20m build ins) )",
  "2026-04-30": "Reykjavíkivi, Iceland (crossfit gym) really good session feel so strong)1-2 sets 10 reps each. Bare Foot\nForward Lunge and Twist\nBackward Lunge \nSide Skip and Squat L & R \nHop and Toe Touch\nSL KBS 4x5 each side RPE 7 - speed focus\nBB Slider Reverse Lunge 4x5 (175,185,185,185) \nSpring Ankle Test 3x20 sec with barbell on back \nHip ISO hold 2x30-45ssec with weight 75lbs straight arm \nInverted Row 3x10-12 reps no weight \nCopenhagen ISO long lever 3x30sec \nStarFish ISO 3x20sec",
  "2026-05-01": "Reykjavíkivi, Iceland (crossfit gym) got so trashed from yesterday couldn't run did the bike \nHurdle Mobility Series R Lead / L Lead Forward – 1 step each Backward – 1 step each High Knee Side Skip – L/R Straight Leg Side Skip – L/R Over-Unders\nSprint Warm-Up 1 Standing A-Skip – 10 each L/R Standing B-Skip – 10 each L/R A-Skip – 20m B-Skip – 20m A-Switches – 20m Triples – 20m Straight Leg Bounds – 1 set\nTempo Runs// did bike cause legs were trashed  10 x 60m// didi this 20x 10sec on 20 sec off 800-900-watts  Vardun Pedestal",
  "2026-05-02": "Reykjavíkivi, Iceland (crossfit gym)\nWarmup on the bike 15x 10sec on 20sec off 900-1000 watts\n(Had to make some substitutes from this training) \n** due to extreme sourness in legs  Front Squat – 4 x 4 Banded Staggered RDL 4x5 each side 35-165lbs Hyperextension + Row – 3 x 6 each Incline Bench Press – 4 x 8 110lbs Hanging Frog Raises – 3 x 10 Hi Hamstring ISO – 2 x 30s each Seated Calf Raise – 3 x 8 \n** added same knee PT",
  "2026-05-03": "Iceland Rest hiked so much Black Sand beach and Puffin Rock",
  "2026-05-04": "Iceland (remote side) snowed and did hills in the snow, Warm Up A Light Aerobics (Nasal Breathing Only) – 5 min Walking Lunge – x10 Inch Worms – x5 Side Skip + Squat – x10 L/R Carioca – x10 L/R Skips Forward – x10 Skips Backward – x10 Leg Swings (Front/Back) – x10 L/R Leg Swings (Side-to-Side) – x10 L/R\nAccel 1 Power Skips – 20m Wall Drill Push – x10 L/R Banded Hip Step – x10 L/R\nAccel 2 Walking Lunge – 20m Wall Drill Push – 6 L / 6 R Half Kneeling Sprint – 3–5 steps Skips for Distance – 20m Drop-In Sprint – 20m  Drop-In Sprint – 1 x 2–3 Hills Track – 1 x 6 50m steep on snowNice sauna and cold plunge therapy 2hours",
  "2026-05-05": "Iceland, on the dock of a fisherman village (flight back to USA 7hr flight then 2hr flight) \n(Had to make some substitutes from this training) \nHip Mobility A Hip Extension Glides – 10 L/R Windscreen Wipers – x10 Windscreen Wipers (Hands Free) – x10\nShake out mobility on the dock \nReverse Banded Walks with thick band 4x30m walk  Alternate Pigeon Pose – x10 Banded Hip Patterning – 2 x 6 each Seated Rocker Box Jump – 2 x 5 Clean Pull – 4 x 4 with a band on dock  Weighted Chin Up – 3 x 4",
  "2026-05-06": "(Landed back in USA ✈️Woodstock LA) Warm Up A Light Aerobics (Nasal Breathing Only) – 5 min Walking Lunge – x10 Inch Worms – x5 Side Skip + Squat – x10 L/R Carioca – x10 L/R Skips Forward – x10 Skips Backward – x10 Leg Swings (Front/Back) – x10 L/R Leg Swings (Side-to-Side) – x10 L/R\nAccel 1 Power Skips – 20m Wall Drill Push – x10 L/R Banded Hip Step – x10 L/R Push Track – 1 x 5 15m on sled 45lbs plate work on reach step in the front Hill Sprints – 1 x 5 30m on steep hill outside \nThrows / Core Explosive Throws Series 1 MB Core Series 1: Complete 1 round\n5-6 throws each\nComplete 1 round\n4-6kg Medicine Ball\n1. OH Backward\n2. Between Legs Forward\n3. Chest Toss Forward \n4. Sprint Start Toss L&R \n5. Side Sling L&R\nCore: \n4-6kg Medicine Ball 10-20 reps each\n1. OH Lateral Reach\n2. OH Straddle \n3. Alternate Toe Touchers \n4. Hip Bridge Lateral Reach\n5. Seated Russian Twist",
  "2026-05-07": "(USA Woodstock LAFitness) MB Warm Up (barefoot, 1-2 sets x 10 reps each)\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat – L/R\nHop and Toe Touch\nAlternate DB Swing – 2 x 15 (RPE 7, speed focus)\nBarbell Slider Reverse Lunge – 3 x 5 each (RPE 8/9)\nSpring Ankle 1 – 2 x 30-45 secs each\nHip Iso Hold – 2 x 30 secs each (RPE 9, add load if able)\nInverted Row – 4 x 10-12 (BW)\nA — Copenhagen Isometric – 2 x 30 secs each (long lever)\nB — Starfish Side Raise – 2 x 10 each",
  "2026-05-08": "(USA Woodstock LAFitness) Hobgood park Hurdle Mobility Series\nRight leg lead / Left leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip – L/R\nStraight Leg Side Skip – L/R\nOver Unders\nSprint Warm Up 1\nStanding A Skip – x10 R/L\nStanding B Skip – x10 R/L\nA-Skip – 20m\nB-Skip – 20m\nA Switches – 20m\nTriples – 20m\nStraight Leg Bound – 1 set x 2 reps @ 20m (left arm overhead)\n60m Tempo Runs – 10 x 60m @ 65-85% (~10.5 secs, on grass/turf in trainers)\nVardun Circuit – 2 rounds x 20 yds each\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\nPedestal – 1 round\nRound 1 Elbow Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Straight Leg Side Kick – x10 L/R\nRound 2 Hand Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Knee Raise Side – x10 L/R\nRound 3 Abs: Side Crunches – x30, Crossfit Sit-Ups – x20",
  "2026-05-09": "(USA Woodstock LAFitness) \nSpinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1min\nHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10\nFront Squat – 4 x 4 (RPE 8) PR: 254\nHyperextension with Row – 3 x 6 each (RPE 8 single leg) PR: 60\nIncline Bench Press – 4 x 8 (RPE 8/9) PR: 139\nHanging Frog Raises – 3 x 10 (controlled)\nHi Hamstring ISO – 2 x 30 secs each\nSeated Calf Raise – 3 x 8 (RPE 8/9)\n\nReady for week 2 whenever you share the link!",
  "2026-05-10": "Rest Paddle Board Marie",
  "2026-05-11": "(USA Woodstock LAFitness) Spinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1minHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10Banded Hip Patterning – 2 x 6 each\nSeated Rocker Box Jump – 2 x 5\nClean Pull – 2 x 4 @ 100% power clean PR 220lbs\nWeighted Chin Up – 2 x 4 (1RIR) 16lbs",
  "2026-05-12": "(Oklahomah CC speeches)✈️ early before flight:Warm Up A\nLight Aerobics (nasal breathing only) – 5 mins\nWalking Lunge – x10\nInch Worms – x5\nSide Skip and Squat – x10 R/L\nCarioca – x10 R/L\nSkips Forward – x10\nSkips Back – x10\nLeg Swings Front/Back – x10 R/L\nLeg Swings Side to Side – x10 R/L\nAccel 1\nPower Skips – 20m\nWall Drill Push – x10 R/L\nBanded Hip Step – x10 R/L\nAccel 2\nWalking Lunge – 20m\nWall Drill Push – 6R/6L\nHalf Kneeling Sprint – 3-5 steps\nSkips for Distance – 20m\nDrop-in Sprint – 20m\nDrop in Sprint – 1 x 2-3 reps @ 20m (uphill)\nPush Track – 1 x 6 (3 reps to 15m, 3 reps to 30m)",
  "2026-05-13": "(Oklahomah CC speeches) Warm Up A\nLight Aerobics (nasal breathing only) – 5 mins\nWalking Lunge – x10\nInch Worms – x5\nSide Skip and Squat – x10 R/L\nCarioca – x10 R/L\nSkips Forward – x10\nSkips Back – x10\nLeg Swings Front/Back – x10 R/L\nLeg Swings Side to Side – x10 R/L\nAccel 1\nPower Skips – 20m\nWall Drill Push – x10 R/L\nBanded Hip Step – x10 R/L (ankle got hurt from the playground with kids needed to just do the bike sprints can't weight bound 15x 12 sec on 25 sec off on resistence with bike in hotel gym . \nHill Track – 1 x 5 (5 brake handle hits to 15m then load or let go)\nHill Sprints – 1 x 5 @ 30m (maximal sprint up steep hill ~10-15 degrees)\nExplosive Throws Series 1 – 1 round, 4-6kg MB, 5-6 throws each\nOH Backward\nBetween Legs Forward\nChest Toss Forward\nSprint Start Toss – L/R\nSide Sling – L/R\nMB Core Series 1 – 1 round, 4-6kg MB, 10-20 reps each\nOH Lateral Reach\nOH Straddle\nAlternate Toe Touchers\nHip Bridge Lateral Reach\nSeated Russian Twist",
  "2026-05-14": "(Texas, Midland Speech)✈️ Hotel Gym AM MB Warm Up (barefoot, 1-2 sets x 10 reps each)\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat – L/R\nHop and Toe Touch\nAlternate DB Swing – 2 x 15 (RPE 7, speed focus)\nBarbell Slider Reverse Lunge – 3 x 5 each (RPE 8/9) (80lbs) \nSpring Ankle 1 – 2 x 30-45 secs each\nHip Iso Hold – 2 x 30 secs each (RPE 9, add load if able)\nInverted Row – 4 x 10-12 (BW)\nA — Copenhagen Isometric – 2 x 30 secs each (long lever)\nB — Starfish Side Raise – 2 x 10 each",
  "2026-05-15": "(Texas, Midland Speech)✈️ Outdoors 6:30am concrete Hurdle Mobility Series\nRight leg lead / Left leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip – L/R\nStraight Leg Side Skip – L/R\nOver Unders\nSprint Warm Up 1\nStanding A Skip – x10 R/L\nStanding B Skip – x10 R/L\nA-Skip – 20m\nB-Skip – 20m\nA Switches – 20m\nTriples – 20m\nStraight Leg Bound – 1 set x 2 reps @ 20m (left arm overhead)\n60m Tempo Runs – 10 x 60m @ 65-85% (~10.5 secs, on grass/turf in trainers)\nVardun Circuit – 2 rounds x 20 yds each\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\nPedestal – 1 round\nRound 1 Elbow Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Straight Leg Side Kick – x10 L/R\nRound 2 Hand Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Knee Raise Side – x10 L/R\nRound 3 Abs: Side Crunches – x30, Crossfit Sit-Ups – x20",
  "2026-05-16": "(Wodstock, GA) Spinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1min\nHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10\nFront Squat – 4 x 4 (RPE 8) PR: 254\nHyperextension with Row – 3 x 6 each (RPE 8 single leg) PR: 60\nIncline Bench Press – 4 x 8 (RPE 8/9) PR: 139\nHanging Frog Raises – 3 x 10 (controlled)\nHi Hamstring ISO – 2 x 30 secs each\nSeated Calf Raise – 3 x 8 (RPE 8/9)",
  "2026-05-18": "Woodstock GA) Hills Deer Run Warm Up A\nLight Aerobics (nasal breathing only) – 5 mins\nWalking Lunge – x10\nInch Worms – x5\nSide Skip and Squat – x10 R/L\nCarioca – x10 R/L\nSkips Forward – x10\nSkips Back – x10\nLeg Swings Front/Back – x10 R/L\nLeg Swings Side to Side – x10 R/L\nAccel 3\nWalking Lunge with Twist – 20m\nWall Drill Push – 6R/6L\nWall Drill Switch – x10\nHalf Kneeling Sprint – 3-5 steps\nReverse Lunge to Half Kneeling Sprint – 15m\nSkips for Distance – 20m\nDrop-in Sprint – 20m\nResisted Sprint Hills– 2 sets x 2-3 reps (Set 1: 20m @ 20k sled / Set 2: 30m @ 15k sled)\nExplosive Throws Series 2 – 1 round, 4-6kg MB, 4-5 throws each\nDrop-in OH Toss\nDrop-in Between Legs Forward\nSLJ to Chest Toss\nLunge to Sprint Start Toss – L/R\nStep-in Side Sling – L/R\nMB Core Series 2 – 1 round, 4-6kg MB, 10-20 reps each\nOH Lateral Reach\nOH Straddle\nAlternate Toe Touchers\nHip Bridge Lateral Reach\nContralateral Hip Bridge\nSeated Russian Twist\nMB Aleknas + PM workout for costa rica travel needs (Spinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1min\nHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10\nFront Squat – 5 x 3 (RPE 8) PR: 254\nHyperextension with Row – 3 x 6 each (RPE 8 single leg) PR: 60\nIncline Bench Press – 4 x 6 (RPE 8/9) PR: 139\nHanging Frog Raises – 3 x 10 (controlled)\nHi Hamstring ISO – 2 x 30 secs each\nSeated Calf Raise – 3 x 8 (RPE 8/9))",
  "2026-05-19": "(Libera, Costa Rica) ✈️Walked all day flight 4am -7pm",
  "2026-05-20": "(Libera, Costa Rica) 7:30am Black Sand beach Hurdle Mobility Series\nRight leg lead / Left leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip – L/R\nStraight Leg Side Skip – L/R\nOver Unders\nSprint Warm Up 2\nAnkle Dribbles – 20m\nShin Dribbles – 20m\nKnee Dribbles – 20m\nB-Skips – 20m\nExtended B-Skip – 20m\nSL Running B's – 20m L/R\nStraight Leg Bound – 1 set x 2 reps @ 20m (left arm overhead)\n60m Tempo Runs – 10 x 60m @ 65-85% (~9.5 secs, on grass/turf in trainers, rest 60s)\nVardun Circuit – 2 rounds x 20 yds each\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\nPedestal – 1 round\nRound 1 Elbow Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Straight Leg Side Kick – x10 L/R\nRound 2 Hand Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Knee Raise Side – x10 L/R\nRound 3 Abs: Side Crunches – x30, Crossfit Sit-Ups – x20",
  "2026-05-21": "(Libera, Costa Rica) The Gym: Spinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1min\nHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10\nBanded Hip Patterning – 2 x 6 each\nSeated Rocker Box Jump – 2 x 5\nAdded Bandded Staggered RDL 4x5/e 165lbs Clean Pull – 3 x 4 @ 105% power clean PR 225lbs\nWeighted Chin Up – 3 x 4 (RPE 8) 25lbs\nBarbell Landmine Oblique Twist – 3 x 10 (RPE 8/9) 50lbs bar",
  "2026-05-22": "(Libera, Costa Rica) Warm Up A\nLight Aerobics (nasal breathing only) – 5 mins\nWalking Lunge – x10\nInch Worms – x5\nSide Skip and Squat – x10 R/L\nCarioca – x10 R/L\nSkips Forward – x10\nSkips Back – x10\nLeg Swings Front/Back – x10 R/L\nLeg Swings Side to Side – x10 R/L\nAccel 1\nPower Skips – 20m\nWall Drill Push – x10 R/L\nBanded Hip Step – x10 R/L\nHill Sprints – 2 sets (Set 1: 6 x 30m / Set 2: 6 x 40m) maximal sprint ~10-15 degrees\nHill Plyos – 1 round (this was all in thick dune sand since no hill for sprints either) \nRepeat Broad Jumps – x3-5\nHops – x3-6\nBound – x3-6",
  "2026-05-23": "(Libera, Costa Rica)✈️ The Gym: MB Warm Up (barefoot, 1-2 sets x 10 reps each)\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat – L/R\nHop and Toe Touch\nAlternate DB Swing – 2 x 15 (RPE 7, speed focus)\nBarbell Slider Reverse Lunge – 3 x 5 each (RPE 8/9) 195,225,235lbs * trashed legs till monday*\nSpring Ankle 1 – 2 x 30-45 secs each\nHip Iso Hold – 2 x 30 secs each (RPE 9, add load if able)\nInverted Row – 4 x 10-12 (BW)\nA — Copenhagen Isometric – 2 x 30 secs each (long lever)\nB — Starfish Side Raise – 2 x 10 each",
  "2026-05-24": "Sunday church / CLT pack to move",
  "2026-05-25": "(Memorial Day) NL certifications Hobgood park with new sled: Warm Up A\nLight Aerobics (nasal breathing only) – 5 mins\nWalking Lunge – x10\nInch Worms – x5\nSide Skip and Squat – x10 R/L\nCarioca – x10 R/L\nSkips Forward – x10\nSkips Back – x10\nLeg Swings Front/Back – x10 R/L\nLeg Swings Side to Side – x10 R/L\nAccel 3\nWalking Lunge with Twist – 20m\nWall Drill Push – 6R/6L\nWall Drill Switch – x10\nHalf Kneeling Sprint – 3-5 steps\nReverse Lunge to Half Kneeling Sprint – 15m\nSkips for Distance – 20m\nDrop-in Sprint – 20m\nResisted Sprint – 2 sets x 2-3 reps (Set 1: 20m @ 20k sled / Set 2: 30m @ 15k sled)\nExplosive Throws Series 2 – 1 round, 4-6kg MB, 4-5 throws each\nDrop-in OH Toss\nDrop-in Between Legs Forward\nSLJ to Chest Toss\nLunge to Sprint Start Toss – L/R\nStep-in Side Sling – L/R\nMB Core Series 2 – 1 round, 4-6kg MB, 10-20 reps each\nOH Lateral Reach\nOH Straddle\nAlternate Toe Touchers\nHip Bridge Lateral Reach\nContralateral Hip Bridge\nSeated Russian Twist\nMB Aleknas",
  "2026-05-26": "(Woodstock, LA) Spinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1min\nHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10\nBarbell Back Squat – 4 x 4 (RPE 8/9) 255\nSL Hamstring Bridge – 3 x 8 each (RPE 8) 65lbs\nBarbell Bench Press – 4 x 5 (RPE 8/9) PR: 146\nHanging Frog Raises – 3 x 10 (controlled)\nHi Hamstring ISO – 2 x 30 secs each\nSeated Calf Raise – 3 x 6 (RPE 8/9)",
  "2026-05-27": "(Woodstock, hobgood) Hurdle Mobility Series\nRight leg lead / Left leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip – L/R\nStraight Leg Side Skip – L/R\nOver Unders\nSprint Warm Up 2\nAnkle Dribbles – 20m\nShin Dribbles – 20m\nKnee Dribbles – 20m\nB-Skips – 20m\nExtended B-Skip – 20m\nSL Running B's – 20m L/R\nStraight Leg Bound – 1 set x 2 reps @ 20m (left arm overhead)\n60m Tempo Runs – 8 x 60m @ 65-85% (~9 secs, on grass/turf in trainers, rest 120s)\nVardun Circuit – 2 rounds x 20 yds each\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\nPedestal – 1 round\nRound 1 Elbow Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Straight Leg Side Kick – x10 L/R\nRound 2 Hand Stand: Straight Leg Back/Front/Side/Medial – x10 L/R, Bent Leg Back/Front – x10 L/R, Knee Raise Side – x10 L/R\nRound 3 Abs: Side Crunches – x30, Crossfit Sit-Ups – x20",
  "2026-05-28": "(Woodstock LA) Spinal Mobility A\nKnee Hug Rolls – x10\nInverted Scissors – x10\nCobras – x10\nCrucifix – x10\nScorpions – x10\nCat Tail – 10 deep breaths L & R\nLat Stretch – 30s-1min\nHip Mobility A\nHip Extension Glides – 10 L/R\nWindscreen Wipers – x10\nWindscreen Wipers (Hands Free) – x10\nAlternate Pigeon Pose – x10\nBanded Hip Patterning – 2 x 6 each 175lbs\nBox Jump – 2 x 5\nClean Speed Pull – 4 x 4 @ 80% power clean PR 200lba\nWeighted Chin Up – 4 sets (x5, x5, x3, x3) RPE 8/9 40lbs\nHalf-Kneeling Landmine Woodchop – 3 x 8 each (RPE 8)",
  "2026-05-29": "(Woodstock Deer Run) Warm Up A\nLight Aerobics (nasal breathing only) – 5 mins\nWalking Lunge – x10\nInch Worms – x5\nSide Skip and Squat – x10 R/L\nCarioca – x10 R/L\nSkips Forward – x10\nSkips Back – x10\nLeg Swings Front/Back – x10 R/L\nLeg Swings Side to Side – x10 R/L\nAccel 2\nWalking Lunge – 20m\nWall Drill Push – 6R/6L\nHalf Kneeling Sprint – 3-5 steps\nSkips for Distance – 20m\nDrop-in Sprint – 20m\nHill Sprints – 1 x 6 @ 50m (maximal sprint ~10-15 degrees)\nHill Plyos – 2 rounds\nRepeat Broad Jumps – x3-5\nHops – x3-6\nBound – x3-6",
  "2026-05-30": "(Woodstock, LA) MB Warm Up (barefoot, 1-2 sets x 10 reps each)\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat – L/R\nHop and Toe Touch\nSL Snatch Step – 2 x 8 each (RPE 7, tech focus)\nSemtex Reverse Slider Lunge – 3 x 5 each (RPE 8/9)\nCalf Iso Hold – 2 x 30 secs each (RPE 9)\nLoaded Hip Iso Hold – 3 x 15 secs each (RPE 9)\nInverted Row – 4 x 10-12 (BW)\nA — Copenhagen Isometric – 2 x 30 secs each (long lever)\nB — Starfish Side Raise – 2 x 10 each",
  "2026-06-01": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 3\n1-2 sets\nWalking Lunge with Twist 20m\nWall Drill Push 6R 6L\nWall Drill Switch 10\nHalf Kneeling Sprint 3-5 steps\nReverse Lunge to Half Kneeling Sprint 15m\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nResisted Sprint - 20x3, 30x3 (meters x reps; Hill sprint, Sled Sprint or Prowler Push, 120s rest)\n\nExplosive Throws Series 2 - 4-5 throws each, complete 1 round, 4-6kg Medicine Ball\n1. Drop-in OH toss\n2. Drop-in Between Legs Forward\n3. SLJ to Chest Toss\n4. Lunge to Sprint Start Toss L&R\n5. Step-in Side Sling L&R\n\nMB Core Series 2\nComplete 1 round, 4-6kg Medicine Ball 10-20 reps\n1. OH Lateral Reach\n2. OH Straddle\n3. Alternate Toe Touchers\n4. Hip Bridge Lateral Reach\n5. Contralateral Hip Bridge\n6. Seated Russian Twist\n7. MB Aleknas",
  "2026-06-02": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBarbell Back Squat - 260x4, 260x4, 270x4, 280x4 (RPE 8/9, rest/FULL)\n\nSL Hamstring Bridge - 75x8, 75x8, 75x8 (RPE 8, tempo: pause at top)\n\nBarbell Bench Press - 120x5, 120x5, 120x5, 120x5 (RPE 8/9, Max: 146)\n\nHanging Frog Raises - 5x10, 5x10, 5x10 (tempo: controlled)\n\nHi Hamstring ISO - 26x30, 26x30 (weight x secs)\n\nSeated Calf Raise - 95x6, 95x6, 95x6",
  "2026-06-03": "Hurdle Mobility Series Right leg lead\nLeft leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip (L,R)\nStraight Leg Side Skip (L,R)\nOver Unders\n\nSprint Warm Up 2\nAnkle Dribbles 20m\nShin Dribbles 20m\nKnee Dribbles 20m\nB Skips 20m\nExtended B Skip 20m\nSL Running B's 20m L,R\n\nstraight leg bound - 2 reps, 20m, holding left arm overhead\n\n60m Tempo Runs - 10.0s, 10.0s, 10.0s, 10.0s, 9.0s, 9.0s, 9.0s, 9.0s\n\nVardun\nComplete 2 rounds, 20 yards each\nVerdun Circuit:\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\n\nPedestal\nComplete 1 round, 3D Core Circuit\nRound 1: Elbow Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Straight Leg Side Kick 10 L,R\nRound 2: Hand Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Knee Raise Side 10 L,R\nRound 3: Abs - Side Crunches 30, Crossfit Situps 20",
  "2026-06-04": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBanded Hip Patterning - 120x6, 120x6\n\nbox jump - 0x5, 0x5\n\nClean Speed Pull - 165x4, 170x4, 170x4, 170x4\n\nWeighted Chin Up - 15x5, 15x5, 20x3, 20x3 (weight added)\n\nHalf-Kneeling Landmine Woodchop - 45x8, 45x8, 45x8",
  "2026-06-05": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 2\nWalking Lunge 20m\nWall Drill Push 6R 6L\nHalf Kneeling Sprint 3-5 steps\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nHill Sprints - 1 x 6 (50m, 120s rest)\nMaximal sprint up steep hill, 10-15 degrees\n\nHill Plyos - 2 rounds, 3 sets each\nRepeat Broad Jumps x3-5, Hops x3-6, Bound x3-6",
  "2026-06-06": "MB Warm Up\n1-2 sets x 10 reps each, bare foot\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat L & R\nHop and Toe Touch\n\nSL Snatch Step - 10x8, 10x8\n\nSemtex Reverse Slider Lunge - 145x5, 155x5, 155x5\n\nCalf Iso Hold - 2-3 x 15-30 secs each (no weight/time value logged)\n\nLoaded Hip Iso Hold - 15s, 15s, 15s each\n\nInverted Row - 95x12, 95x12, 95x12, 95x12\n\nA - Copenhagen Isometric - 0x30, 0x30 (long lever)\n\nB - Starfish Side Raise - 10x10, 10x10",
  "2026-06-07": "Rest Day\nNo workout scheduled",
  "2026-06-08": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 3\n1-2 sets\nWalking Lunge with Twist 20m\nWall Drill Push 6R 6L\nWall Drill Switch 10\nHalf Kneeling Sprint 3-5 steps\nReverse Lunge to Half Kneeling Sprint 15m\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nResisted Sprint - 20x3, 30x3 (meters x reps; Hill sprint, Sled Sprint or Prowler Push, 120s rest)\n\nExplosive Throws Series 2 - 4-5 throws each, complete 1 round, 4-6kg Medicine Ball\n1. Drop-in OH toss\n2. Drop-in Between Legs Forward\n3. SLJ to Chest Toss\n4. Lunge to Sprint Start Toss L&R\n5. Step-in Side Sling L&R\n\nMB Core Series 2\nComplete 1 round, 4-6kg Medicine Ball 10-20 reps\n1. OH Lateral Reach\n2. OH Straddle\n3. Alternate Toe Touchers\n4. Hip Bridge Lateral Reach\n5. Contralateral Hip Bridge\n6. Seated Russian Twist\n7. MB Aleknas",
  "2026-06-09": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBarbell Back Squat - 245x4, 265x4, 275x4, 275x4 (RPE 8/9, rest/FULL)\n\nSL Hamstring Bridge - 75x8, 80x8, 80x8 (RPE 8)\n\nBarbell Bench Press - 135x5, 145x5, 145x5, 150x4 (RPE 8/9, Max: 146)\n\nHanging Frog Raises - 0x10, 0x10, 0x10 (tempo: controlled)\n\nHi Hamstring ISO - 44x30, 44x30 (weight x secs)\n\nSeated Calf Raise - 45x6, 45x6, 45x6\n\nNEW PR: Barbell Bench Press 164",
  "2026-06-10": "Hurdle Mobility Series Right leg lead\nLeft leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip (L,R)\nStraight Leg Side Skip (L,R)\nOver Unders\n\nSprint Warm Up 2\nAnkle Dribbles 20m\nShin Dribbles 20m\nKnee Dribbles 20m\nB Skips 20m\nExtended B Skip 20m\nSL Running B's 20m L,R\n\nstraight leg bound - 2 reps, 20m, holding left arm overhead\n\n60m Tempo Runs - 10.3s, 8.9s, 8.9s, 8.9s, 9.9s, 8.8s, 8.8s, 8.8s\n\nVardun\nComplete 2 rounds, 20 yards each\nVerdun Circuit:\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\n\nPedestal\nComplete 1 round, 3D Core Circuit\nRound 1: Elbow Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Straight Leg Side Kick 10 L,R\nRound 2: Hand Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Knee Raise Side 10 L,R\nRound 3: Abs - Side Crunches 30, Crossfit Situps 20",
  "2026-06-11": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBanded Hip Patterning - 150x6, 150x6\n\nbox jump - 8x5, 8x5\n\nClean Speed Pull - 165x4, 165x4, 165x4, 168x4\n\nWeighted Chin Up - 15x5, 20x5, 25x3, 30x3 (weight added)\n\nHalf-Kneeling Landmine Woodchop - 40x8, 40x8, 40x8",
  "2026-06-12": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 2\nWalking Lunge 20m\nWall Drill Push 6R 6L\nHalf Kneeling Sprint 3-5 steps\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nHill Sprints - 1 x 6 (50m, 120s rest)\nMaximal sprint up steep hill, 10-15 degrees\n\nHill Plyos - 2 rounds, 3 sets each\nRepeat Broad Jumps x3-5, Hops x3-6, Bound x3-6",
  "2026-06-13": "MB Warm Up\n1-2 sets x 10 reps each, bare foot\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat L & R\nHop and Toe Touch\n\nSL Snatch Step - 10x8, 10x8\n\nSemtex Reverse Slider Lunge - 150x5, 150x5, 150x5\n\nCalf Iso Hold - 2-3 x 15-30 secs each (no weight/time value logged)\n\nLoaded Hip Iso Hold - 15s, 15s, 15s each\n\nInverted Row - 0x12, 0x12, 0x12, 0x12\n\nA - Copenhagen Isometric - 5x30, 5x30 (long lever)\n\nB - Starfish Side Raise - 8x10, 8x10",
  "2026-06-14": "Rest Day\nNo workout scheduled",
  "2026-06-15": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 3\n1-2 sets\nWalking Lunge with Twist 20m\nWall Drill Push 6R 6L\nWall Drill Switch 10\nHalf Kneeling Sprint 3-5 steps\nReverse Lunge to Half Kneeling Sprint 15m\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nResisted Sprint - 20x3, 30x3 (meters x reps; Hill sprint, Sled Sprint or Prowler Push, 120s rest)\n\nSprint - 40m (reps not logged)\n\nExplosive Throws Series 3 - 3-4 throws each, complete 1 round, 4-6kg Medicine Ball\n1. Forward Jump to OH Toss\n2. Forward Jump to Between Legs Forward\n3. 2xSLJ to Chest Toss\n4. Vertical Jump to Sprint Start Toss L&R\n5. Heiden Bound to Side Sling L&R\n\nMB Core Series 2\nComplete 1 round, 4-6kg Medicine Ball 10-20 reps\n1. OH Lateral Reach\n2. OH Straddle\n3. Alternate Toe Touchers\n4. Hip Bridge Lateral Reach\n5. Contralateral Hip Bridge\n6. Seated Russian Twist\n7. MB Aleknas",
  "2026-06-16": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBarbell Back Squat - 270x3, 300x3, 300x3, 270x3, 270x3 (RPE 8/9, rest/FULL)\n\nSupramax Hamstring Bridge - 65x5, 65x5, 65x5 (RPE 9+ eccentric)\n\nBarbell Bench Press - 140x4, 145x4, 150x4, 155x4 (RPE 8/9, Max: 164)\n\nHanging Double Leg Eagles - 0x10, 0x10, 0x10 (tempo: controlled)\n\nSoleus Isometric - 155x5s, 155x5s, 155x5s, 155x5s, 155x5s (max iso push)\n\nNEW PR: Barbell Bench Press 169",
  "2026-06-17": "Hurdle Mobility Series\nRight leg lead\nLeft leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip (L,R)\nStraight Leg Side Skip (L,R)\nOver Unders\n\nSprint Warm Up 2\nAnkle Dribbles 20m\nShin Dribbles 20m\nKnee Dribbles 20m\nB Skips 20m\nExtended B Skip 20m\nSL Running B's 20m L,R\n\nstraight leg bound - 3 reps, light sled w/ waist harness, 20m\n\n60m Tempo Runs - 10.0s, 9.5s, 9.5s, 9.0s, 9.0s, 9.0s, 9.0s, 8.8s, 8.8s, 8.0s\n\nVardun\nComplete 2 rounds, 20 yards each\nVerdun Circuit:\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\n\nPedestal\nComplete 1 round, 3D Core Circuit\nRound 1: Elbow Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Straight Leg Side Kick 10 L,R\nRound 2: Hand Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Knee Raise Side 10 L,R\nRound 3: Abs - Side Crunches 30, Crossfit Situps 20",
  "2026-06-18": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBanded Hip Patterning - 175x6, 185x6\n\nDB Drop to Box Jump - 45x5, 45x5, 45x5 (20kg DBs)\n\nPower Clean - 175x3, 185x3, 185x3, 185x3 (RPE 8/9, rest/FULL; NEW PR 185)\n\nPush Press - 125x5, 145x5, 145x5, 155x5 (RPE 8)\n\nWeighted Chin Up - +25x3, +25x3, +35x2, +35x2 (RPE 8/9)\n\nSide Plank DB rotation - 12.5x10, 15x10, 15x10 (RPE 8)",
  "2026-06-19": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 2\nWalking Lunge 20m\nWall Drill Push 6R 6L\nHalf Kneeling Sprint 3-5 steps\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nResisted Sprint - 30x5, 40x5 (meters x reps, waist harness 10kg, 180s reps, 240s rest)\n\nHorizontal Jumps - 1 round\nStanding Long Jump, 3x Standing Long Jump, Standing Triple Jump",
  "2026-06-20": "MB Warm Up\n1-2 sets x 10 reps each, bare foot\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat L & R\nHop and Toe Touch\n\nSL Snatch Step - 10x6, 10x6, 10x6\n\nSemtex Reverse Slider Lunge - 155x4, 175x4, 210x4, 210x4\n\nCalf Iso Hold - 2-3 x 15-30 secs each (no weight/time value logged)\n\nLoaded Hip Iso Hold - 7s, 7s, 7s, 7s each\n\nInverted Row - 115x10, 115x10, 115x12, 155x12\n\nA - Copenhagen Isometric - 0x30, 0x30, 0x30 (long lever)\n\nB - Starfish Side Raise - 0x10, 0x10, 0x10",
  "2026-06-21": "Rest Day\nNo workout scheduled",
  "2026-06-22": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 3\n1-2 sets\nWalking Lunge with Twist 20m\nWall Drill Push 6R 6L\nWall Drill Switch 10\nHalf Kneeling Sprint 3-5 steps\nReverse Lunge to Half Kneeling Sprint 15m\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nResisted Sprint - 20x3, 30x3 (meters x reps; Hill sprint, Sled Sprint or Prowler Push, 120s rest)\n\nExplosive Throws Series 2 - 4-5 throws each, complete 1 round, 4-6kg Medicine Ball\n1. Drop-in OH toss\n2. Drop-in Between Legs Forward\n3. SLJ to Chest Toss\n4. Lunge to Sprint Start Toss L&R\n5. Step-in Side Sling L&R\n\nMB Core Series 2\nComplete 1 round, 4-6kg Medicine Ball 10-20 reps\n1. OH Lateral Reach\n2. OH Straddle\n3. Alternate Toe Touchers\n4. Hip Bridge Lateral Reach\n5. Contralateral Hip Bridge\n6. Seated Russian Twist\n7. MB Aleknas",
  "2026-06-23": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBarbell Back Squat - 225x4, 235x4, 240x4, 260x4 (RPE 8/9, rest/FULL)\n\nSL Hamstring Bridge - 65x8, 65x8, 65x8 (RPE 8)\n\nBarbell Bench Press - 95x5, 115x5, 125x5, 125x5 (RPE 8/9, Max: 169)\n\nHanging Frog Raises - 0x10, 0x10, 0x10 (tempo: controlled)\n\nHi Hamstring ISO - 85x30, 85x30 (weight x secs)\n\nSeated Calf Raise - 85x6, 85x6, 85x6",
  "2026-06-24": "Hurdle Mobility Series Right leg lead\nLeft leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip (L,R)\nStraight Leg Side Skip (L,R)\nOver Unders\n\nSprint Warm Up 2\nAnkle Dribbles 20m\nShin Dribbles 20m\nKnee Dribbles 20m\nB Skips 20m\nExtended B Skip 20m\nSL Running B's 20m L,R\n\nstraight leg bound - 1 set (2 reps, 20m, holding left arm overhead)\n\n60m Tempo Runs - 8 sets (65-85% intensity, 120s rest)\n\nVardun\nComplete 2 rounds, 20 yards each\nVerdun Circuit:\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\n\nPedestal\nComplete 1 round, 3D Core Circuit\nRound 1: Elbow Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Straight Leg Side Kick 10 L,R\nRound 2: Hand Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Knee Raise Side 10 L,R\nRound 3: Abs - Side Crunches 30, Crossfit Situps 20",
  "2026-06-25": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBanded Hip Patterning - 120x6, 120x6\n\nbox jump - 0x5, 0x5\n\nClean Speed Pull - 170x4, 170x4, 170x4, 170x4\n\nWeighted Chin Up - 12x5, 12x5, 12x3, 12x3 (weight added)\n\nHalf-Kneeling Landmine Woodchop - 45x8, 45x8, 45x8",
  "2026-06-26": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 2\nWalking Lunge 20m\nWall Drill Push 6R 6L\nHalf Kneeling Sprint 3-5 steps\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nHill Sprints - 1 x 6 (50m, 120s rest)\nMaximal sprint up steep hill, 10-15 degrees\n\nHill Plyos - 2 rounds, 3 sets each\nRepeat Broad Jumps x3-5, Hops x3-6, Bound x3-6",
  "2026-06-27": "MB Warm Up\n1-2 sets x 10 reps each, bare foot\nForward Lunge and Twist\nBackward Lunge\nSide Skip and Squat L & R\nHop and Toe Touch\n\nSL Snatch Step - 10x8, 10x8\n\nSemtex Reverse Slider Lunge - 170x5, 210x5, 210x5\n\nCalf Iso Hold - 2-3 x 15-30 secs each (no weight/time value logged)\n\nLoaded Hip Iso Hold - 15s, 15s, 15s each\n\nInverted Row - 115x10, 115x10, 115x10, 115x10\n\nA - Copenhagen Isometric - 0x30, 0x30 (long lever)\n\nB - Starfish Side Raise - 0x10, 0x10",
  "2026-06-28": "Rest Day\nNo workout scheduled",
  "2026-06-29": "Warm Up A\nLight Aerobics (nasal breathing only) 5mins\nWalking Lunge x10\nInch Worms x5\nSide Skip and Squat x10 R,L\nCarioca x10 R,L\nSkips Forward x10\nSkips Back x10\nLeg Swings front back x10 R,L\nLeg Swings side to side x10 R,L\n\nAccel 3\n1-2 sets\nWalking Lunge with Twist 20m\nWall Drill Push 6R 6L\nWall Drill Switch 10\nHalf Kneeling Sprint 3-5 steps\nReverse Lunge to Half Kneeling Sprint 15m\nSkips for Distance 20m\nDrop-in Sprint 20m\n\nResisted Sprint - 20m, 30m (reps not logged - MISSED / not completed)\n\nExplosive Throws Series 2 - 4-5 throws each, complete 1 round, 4-6kg Medicine Ball\n1. Drop-in OH toss\n2. Drop-in Between Legs Forward\n3. SLJ to Chest Toss\n4. Lunge to Sprint Start Toss L&R\n5. Step-in Side Sling L&R\n\nMB Core Series 2\nComplete 1 round, 4-6kg Medicine Ball 10-20 reps\n1. OH Lateral Reach\n2. OH Straddle\n3. Alternate Toe Touchers\n4. Hip Bridge Lateral Reach\n5. Contralateral Hip Bridge\n6. Seated Russian Twist\n7. MB Aleknas",
  "2026-06-30": "Spinal Mobility A\nKnee Hug Rolls x10, Inverted Scissors x10, Cobras x10, Crucifix x10, Scorpions x10, Cat Tail 10 deep breaths L&R, Lat Stretch 30s-1min\nHip Mobility A\nHip Extension Glides 10 R,L, Windscreen Wipers 10, Windscreen Wipers (hands free) 10, Alternate Pigeon Pose 10\n\nBarbell Back Squat - 225x4, 235x4, 245x4, 250x4 (RPE 8/9, rest/FULL)\n\nSL Hamstring Bridge - 25x8, 25x8, 25x8 (RPE 8)\n\nBarbell Bench Press - 150x5, 165x5, 165x5, 165x5 (RPE 8/9, Max: 169)\n\nHanging Frog Raises - 0x10, 0x10, 0x10 (tempo: controlled)\n\nHi Hamstring ISO - 25x30, 25x30 (weight x secs)\n\nSeated Calf Raise - 55x6, 55x6, 55x6\n\nNEW PR: Barbell Bench Press 186"
 },
 "videos": {
  "2026-01-13": "https://www.youtube.com/watch?v=RRP-vkar6_0",
  "2026-01-16": "https://www.youtube.com/watch?v=b41H_569mXY",
  "2026-01-20": "https://www.youtube.com/watch?v=RRP-vkar6_0",
  "2026-02-09": "https://www.youtube.com/watch?v=Z2-aT1x0OLI",
  "2026-02-11": "https://www.youtube.com/watch?v=Sa5Fs5gw6R8",
  "2026-02-18": "https://www.youtube.com/watch?v=Sa5Fs5gw6R8",
  "2026-02-25": "https://www.youtube.com/watch?v=Sa5Fs5gw6R8",
  "2026-03-30": "https://www.youtube.com/watch?v=Y8lQLMBpW3o",
  "2026-04-10": "https://www.youtube.com/watch?v=bgFCsOf3-q4",
  "2026-04-20": "https://www.youtube.com/watch?v=CNQgtIzq-pE",
  "2026-04-21": "https://www.youtube.com/watch?v=P5PlbiAw_o8",
  "2026-05-01": "https://www.youtube.com/watch?v=-vmSDI4kQbo",
  "2026-05-30": "https://www.youtube.com/watch?v=gJE00Uqj1Qg&t=9s",
  "2026-06-01": "https://www.youtube.com/watch?v=qW_aR3N3QyI",
  "2026-06-02": "https://www.youtube.com/watch?v=ePHYIZIyomI",
  "2026-06-03": "https://www.youtube.com/watch?v=O30WXF2RD64",
  "2026-06-04": "https://www.youtube.com/watch?v=GJlPAdzITHs",
  "2026-06-05": "https://www.youtube.com/watch?v=d5GbwOKDmbU",
  "2026-06-06": "https://www.youtube.com/watch?v=gJE00Uqj1Qg",
  "2026-06-08": "https://www.youtube.com/watch?v=qW_aR3N3QyI",
  "2026-06-09": "https://www.youtube.com/watch?v=ePHYIZIyomI",
  "2026-06-10": "https://www.youtube.com/watch?v=O30WXF2RD64",
  "2026-06-11": "https://www.youtube.com/watch?v=GJlPAdzITHs",
  "2026-06-12": "https://www.youtube.com/watch?v=d5GbwOKDmbU",
  "2026-06-13": "https://www.youtube.com/watch?v=gJE00Uqj1Qg",
  "2026-06-15": "https://www.youtube.com/watch?v=3iQPVKNuVnY",
  "2026-06-16": "https://www.youtube.com/watch?v=ePHYIZIyomI",
  "2026-06-17": "https://www.youtube.com/watch?v=O30WXF2RD64",
  "2026-06-18": "https://www.youtube.com/watch?v=GJlPAdzITHs",
  "2026-06-19": "https://www.youtube.com/watch?v=y_gnO4qmUZA",
  "2026-06-20": "https://www.youtube.com/watch?v=thmXOWHbvYY",
  "2026-06-22": "https://www.youtube.com/watch?v=qW_aR3N3QyI",
  "2026-06-23": "https://www.youtube.com/watch?v=ePHYIZIyomI",
  "2026-06-24": "https://www.youtube.com/watch?v=O30WXF2RD64",
  "2026-06-25": "https://www.youtube.com/watch?v=9AgHkFMEm1I",
  "2026-06-26": "https://www.youtube.com/watch?v=d5GbwOKDmbU",
  "2026-06-27": "https://www.youtube.com/watch?v=gJE00Uqj1Qg"
 },
 "monthNotes": {
  "January": "JANUARY- Switzerland, Germany started back with Eric to stay more structered on my sprint game Connor wasn't",
  "February": "FEBRUARY- Cortina Olympic preperation working with Eric",
  "March": "MARCH-Post Olympics Holiday and Travel with Francesco planning off season Eric coaching me",
  "April": "APRIL- at a push track in Northern Italy (renting 3 weeks) struggling with post olympic blue, have been to 33 counteries and 50 cities since October",
  "June": "Hurdle Mobility Series\nRight leg lead\nLeft leg lead\nForwards 1 step each\nBackwards 1 step each\nHigh Knee Side Skip (L,R)\nStraight Leg Side Skip (L,R)\nOver Unders\n\nSprint Warm Up 2\nAnkle Dribbles 20m\nShin Dribbles 20m\nKnee Dribbles 20m\nB Skips 20m\nExtended B Skip 20m\nSL Running B's 20m L,R\n\nstraight leg bound - 2 reps, 20m, holding left arm overhead\n\n60m Tempo Runs - 10.0s, 10.0s, 10.0s, 10.0s, 9.0s, 9.0s, 9.0s, 9.0s\n\nVardun\nComplete 2 rounds, 20 yards each\nVerdun Circuit:\nLow Walks Forward\nLow Walks Backward\nDuck Lunge Walks\nLateral Duck Walks\nLunge Extension Walks\nLow Walks Lateral\nDuck Walk\n\nPedestal\nComplete 1 round, 3D Core Circuit\nRound 1: Elbow Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Straight Leg Side Kick 10 L,R\nRound 2: Hand Stand - Straight Leg Back/Front/Side/Medial 10 L,R, Bent Leg Back/Front 10 L,R, Knee Raise Side 10 L,R\nRound 3: Abs - Side Crunches 30, Crossfit Situps 20"
 },
 "generated": "2026-08-18"
};
